using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RCT2GA.RideData
{
    class RCT2RideCode
    {
        public enum RCT2TrackName
        {
            SpiralRollerCoaster,
            StandupRollerCoaster,
            SuspendedSwingingCoasterStandard,
            SuspendedSwingingCoasterAirplane,
            SuspendedSwingingCoasterFloorless,
            InvertedRollerCoaster,
            JuniorRollerCoasterLadybird,
            JuniorRollerCoasterLogTrain,
            MiniatureRailwayStandard,
            MiniatureRailwayAmerican,
            MiniatureRailwayCovered,
            Trams,
            MonorailLarge,
            MonorailSmall,
            MonorailRetro,
            MiniSuspendedCoaster,
            MiniSuspendedFlyingCoaster,
            BumperBoats,
            Canoes,
            RowingBoats,
            Swans,
            WaterTricycles,
            JetSkis,
            WoodenWildMineRide,
            WoodenWildMouse,
            Steeplechase,
            MotorbikeRaces,
            SoapBoxDerbyRacers,
            CarRidePickUps,
            CarRideRaceCars,
            CarRideSportsCars,
            CheshireCats,
            VintageCars,
            MonsterTrucks,
            LaunchedFreefall,
            BobsleighCoaster,
            FlyingTurns,
            ObservationTower,
            DoubleDeckObservationTower,
            LoopingRollerCoaster,
            DinghySlide,
            MineTrainCoaster,
            ChairliftStandard,
            CharliftSkiLift,
            CorkscrewRollerCoaster,
            HyperCoaster,
            Maze,
            SpiralSlide,
            GoKarts,
            LogFlume,
            RiverRapids,
            BumperCards,
            PirateShip,
            SwingingInverterShip,
            FoodStall,
            DrinkStall,
            Shop,
            MerryGoRound,
            InformationKiosk,
            Bathroom,
            FerrisWheel,
            MotionSimulator,
            Cinema3D,
            TopSpin,
            SpaceRings,
            ReverseFreefallCoaster,
            Elevator,
            VerticalDropRollerCoaster,
            ATM,
            Twist,
            SnowCups,
            HauntedHouse,
            FirstAid,
            CircusShow,
            GhostTrain,
            HauntedMansionRide,
            TwisterRollerCoaster,
            FloorlessRollerCoaster,
            StandupTwisterCoaster,
            HyperTwisterRollerCoasterWide,
            HyperTwisterRollerCoasterNarrow,
            WoodenRollerCoasterArticulated,
            WoodenRollerCoaster4Seater,
            WoodenRollerCoaster6Seater,
            WoodenRollerCoaster6SeaterReversed,
            SideFrictionRollerCoaster,
            WildMouseMouseCars,
            WildMouseMineCars,
            SpinningWildMouse,
            MultiDimensionRollerCoaster,
            FlyingRollerCoaster,
            VirginiaReel,
            SplashBoats,
            MiniHelicopters,
            LaydownRollerCoaster,
            SuspendedMonorail,
            ReverserRollerCoaster,
            HeartlineTwisterCoasterStandard,
            HeartlineTwisterCoasterReversed,
            MiniGolf,
            GigaCoaster,
            RotoDrop,
            FlyingSaucers,
            CrookedHouse,
            MonorailCycles,
            CompactInvertedCoaster,
            InvertedShuttleCoaster,
            InvertedVerticleShuttle,
            WaterCoaster,
            AirPoweredVerticalCoaster,
            InvertedHairpinCoaster,
            MagicCarpet,
            SubmarineRide,
            RiverRafts,
            Enterprise,
            InvertedImpulseCoaster,
            MiniRollerCoasterAutomobile,
            MiniRollerCoasterRocket,
            MiniRollerCoasterTobbogan,
            MineRide,
            LIMLaunchedRollerCoaster
        };

        public static Dictionary<RCT2TrackName, int> RideNameCodeMap = new Dictionary<RCT2TrackName, int>
        {
            { RCT2TrackName.SpiralRollerCoaster, 0x0 },
            { RCT2TrackName.StandupRollerCoaster, 0x1 },
            { RCT2TrackName.SuspendedSwingingCoasterStandard, 0x2 },
            { RCT2TrackName.SuspendedSwingingCoasterAirplane, 0x2 },
            { RCT2TrackName.SuspendedSwingingCoasterFloorless, 0x2 },
            { RCT2TrackName.InvertedRollerCoaster, 0x3 },
            { RCT2TrackName.JuniorRollerCoasterLadybird, 0x4 },
            { RCT2TrackName.JuniorRollerCoasterLogTrain, 0x4 },
            { RCT2TrackName.MiniatureRailwayStandard, 0x5 },
            { RCT2TrackName.MiniatureRailwayAmerican, 0x5 },
            { RCT2TrackName.MiniatureRailwayCovered, 0x5 },
            { RCT2TrackName.Trams, 0x5 },
            { RCT2TrackName.MonorailLarge, 0x6 },
            { RCT2TrackName.MonorailSmall, 0x6 },
            { RCT2TrackName.MonorailRetro, 0x6 },
            { RCT2TrackName.MiniSuspendedCoaster, 0x7 },
            { RCT2TrackName.MiniSuspendedFlyingCoaster, 0x7 },
            { RCT2TrackName.BumperBoats, 0x8 },
            { RCT2TrackName.Canoes, 0x8 },
            { RCT2TrackName.RowingBoats, 0x8 },
            { RCT2TrackName.Swans, 0x8 },
            { RCT2TrackName.WaterTricycles, 0x8 },
            { RCT2TrackName.JetSkis, 0x8 },
            { RCT2TrackName.WoodenWildMineRide, 0x9 },
            { RCT2TrackName.WoodenWildMouse, 0x9 },
            { RCT2TrackName.Steeplechase, 0xA },
            { RCT2TrackName.MotorbikeRaces, 0xA },
            { RCT2TrackName.SoapBoxDerbyRacers, 0xA },
            { RCT2TrackName.CarRidePickUps, 0xB },
            { RCT2TrackName.CarRideRaceCars, 0xB },
            { RCT2TrackName.CarRideSportsCars, 0xB },
            { RCT2TrackName.CheshireCats, 0xB },
            { RCT2TrackName.VintageCars, 0xB },
            { RCT2TrackName.MonsterTrucks, 0xB },
            { RCT2TrackName.LaunchedFreefall, 0xC },
            { RCT2TrackName.BobsleighCoaster, 0xD },
            { RCT2TrackName.FlyingTurns, 0xD },
            { RCT2TrackName.ObservationTower, 0xE },
            { RCT2TrackName.DoubleDeckObservationTower, 0xE },
            { RCT2TrackName.LoopingRollerCoaster, 0xF },
            { RCT2TrackName.DinghySlide, 0x10 },
            { RCT2TrackName.MineTrainCoaster, 0x11 },
            { RCT2TrackName.ChairliftStandard, 0x12 },
            { RCT2TrackName.CharliftSkiLift, 0x12 },
            { RCT2TrackName.CorkscrewRollerCoaster, 0x13 },
            { RCT2TrackName.HyperCoaster, 0x13 },
            { RCT2TrackName.Maze, 0x14 },
            { RCT2TrackName.SpiralSlide, 0x15 },
            { RCT2TrackName.GoKarts, 0x16 },
            { RCT2TrackName.LogFlume, 0x17 },
            { RCT2TrackName.RiverRapids, 0x18 },
            { RCT2TrackName.BumperCards, 0x19 },
            { RCT2TrackName.PirateShip, 0x1A },
            { RCT2TrackName.SwingingInverterShip, 0x1B },
            { RCT2TrackName.FoodStall, 0x1C },
            { RCT2TrackName.DrinkStall, 0x1E },
            { RCT2TrackName.Shop, 0x20 },
            { RCT2TrackName.MerryGoRound, 0x21 },
            { RCT2TrackName.InformationKiosk, 0x23 },
            { RCT2TrackName.Bathroom, 0x24 },
            { RCT2TrackName.FerrisWheel, 0x25 },
            { RCT2TrackName.MotionSimulator, 0x26 },
            { RCT2TrackName.Cinema3D, 0x27 },
            { RCT2TrackName.TopSpin, 0x28 },
            { RCT2TrackName.SpaceRings, 0x29 },
            { RCT2TrackName.ReverseFreefallCoaster, 0x2A },
            { RCT2TrackName.Elevator, 0x2B },
            { RCT2TrackName.VerticalDropRollerCoaster, 0x2C },
            { RCT2TrackName.ATM, 0x2D },
            { RCT2TrackName.Twist, 0x2E },
            { RCT2TrackName.SnowCups, 0x2E },
            { RCT2TrackName.HauntedHouse, 0x2D },
            { RCT2TrackName.FirstAid, 0x30 },
            { RCT2TrackName.CircusShow, 0x31 },
            { RCT2TrackName.GhostTrain, 0x32 },
            { RCT2TrackName.HauntedMansionRide, 0x32 },
            { RCT2TrackName.TwisterRollerCoaster, 0x33 },
            { RCT2TrackName.FloorlessRollerCoaster, 0x33 },
            { RCT2TrackName.StandupTwisterCoaster, 0x33 },
            { RCT2TrackName.HyperTwisterRollerCoasterWide, 0x33 },
            { RCT2TrackName.HyperTwisterRollerCoasterNarrow, 0x33 },
            { RCT2TrackName.WoodenRollerCoasterArticulated, 0x34 },
            { RCT2TrackName.WoodenRollerCoaster4Seater, 0x34 },
            { RCT2TrackName.WoodenRollerCoaster6Seater, 0x34 },
            { RCT2TrackName.WoodenRollerCoaster6SeaterReversed, 0x34 },
            { RCT2TrackName.SideFrictionRollerCoaster, 0x35 },
            { RCT2TrackName.WildMouseMouseCars, 0x36 },
            { RCT2TrackName.WildMouseMineCars, 0x36 },
            { RCT2TrackName.SpinningWildMouse, 0x36 },
            { RCT2TrackName.MultiDimensionRollerCoaster, 0x37 },
            { RCT2TrackName.FlyingRollerCoaster, 0x39 },
            { RCT2TrackName.VirginiaReel, 0x3B },
            { RCT2TrackName.SplashBoats, 0x3C },
            { RCT2TrackName.MiniHelicopters, 0x3D },
            { RCT2TrackName.LaydownRollerCoaster, 0x3E },
            { RCT2TrackName.SuspendedMonorail, 0x3F },
            { RCT2TrackName.ReverserRollerCoaster, 0x41 },
            { RCT2TrackName.HeartlineTwisterCoasterStandard, 0x42 },
            { RCT2TrackName.HeartlineTwisterCoasterReversed, 0x42 },
            { RCT2TrackName.MiniGolf, 0x43 },
            { RCT2TrackName.GigaCoaster, 0x44 },
            { RCT2TrackName.RotoDrop, 0x45 },
            { RCT2TrackName.FlyingSaucers, 0x46 },
            { RCT2TrackName.CrookedHouse, 0x47 },
            { RCT2TrackName.MonorailCycles, 0x48 },
            { RCT2TrackName.CompactInvertedCoaster, 0x49 },
            { RCT2TrackName.InvertedShuttleCoaster, 0x49 },
            { RCT2TrackName.InvertedVerticleShuttle, 0x49 },
            { RCT2TrackName.WaterCoaster, 0x4A },
            { RCT2TrackName.AirPoweredVerticalCoaster, 0x4B },
            { RCT2TrackName.InvertedHairpinCoaster, 0x4C },
            { RCT2TrackName.MagicCarpet, 0x4D },
            { RCT2TrackName.SubmarineRide, 0x4E },
            { RCT2TrackName.RiverRafts, 0x4F },
            { RCT2TrackName.Enterprise, 0x51 },
            { RCT2TrackName.InvertedImpulseCoaster, 0x56 },
            { RCT2TrackName.MiniRollerCoasterAutomobile, 0x57 },
            { RCT2TrackName.MiniRollerCoasterRocket, 0x57 },
            { RCT2TrackName.MiniRollerCoasterTobbogan, 0x57 },
            { RCT2TrackName.MineRide, 0x58 },
            { RCT2TrackName.LIMLaunchedRollerCoaster, 0x5A },
        };

        public static Dictionary<RCT2TrackName, string> RideNameVehicleMap = new Dictionary<RCT2TrackName, string>
        {
            { RCT2TrackName.SpiralRollerCoaster, "SPDRCR" },
            { RCT2TrackName.StandupRollerCoaster, "TOGST" },
            { RCT2TrackName.SuspendedSwingingCoasterStandard, "ARRSW1" },
            { RCT2TrackName.SuspendedSwingingCoasterAirplane, "ARRSW2" },
            { RCT2TrackName.SuspendedSwingingCoasterFloorless, "VEKVAMP" },
            { RCT2TrackName.InvertedRollerCoaster, "NEMT" },
            { RCT2TrackName.JuniorRollerCoasterLadybird, "ZLDB" },
            { RCT2TrackName.JuniorRollerCoasterLogTrain, "ZLOG" },
            { RCT2TrackName.MiniatureRailwayStandard, "NRL" },
            { RCT2TrackName.MiniatureRailwayAmerican, "AML1" },
            { RCT2TrackName.MiniatureRailwayCovered, "NRL2" },
            { RCT2TrackName.Trams, "TRAM1" },
            { RCT2TrackName.MonorailLarge, "MONO1" },
            { RCT2TrackName.MonorailSmall, "MONO2" },
            { RCT2TrackName.MonorailRetro, "MONO3" },
            { RCT2TrackName.MiniSuspendedCoaster, "BATFL" },
            { RCT2TrackName.MiniSuspendedFlyingCoaster, "SKYTR" },
            { RCT2TrackName.BumperBoats, "BBOAT" },
            { RCT2TrackName.Canoes, "CBOAT" },
            { RCT2TrackName.RowingBoats, "RBOAT" },
            { RCT2TrackName.Swans, "SWANS" },
            { RCT2TrackName.WaterTricycles, "TRIKE" },
            { RCT2TrackName.JetSkis, "JSKI" },
            { RCT2TrackName.WoodenWildMineRide, "WMMINE" },
            { RCT2TrackName.WoodenWildMouse, "WMOUSE" },
            { RCT2TrackName.Steeplechase, "STEEP1" },
            { RCT2TrackName.MotorbikeRaces, "STEEP2" },
            { RCT2TrackName.SoapBoxDerbyRacers, "SBOX" },
            { RCT2TrackName.CarRidePickUps, "TRUCK1" },
            { RCT2TrackName.CarRideRaceCars, "RCR" },
            { RCT2TrackName.CarRideSportsCars, "SPCAR" },
            { RCT2TrackName.CheshireCats, "CTCAR" },
            { RCT2TrackName.VintageCars, "VCR" },
            { RCT2TrackName.MonsterTrucks, "4X4" },
            { RCT2TrackName.LaunchedFreefall, "SSC1" },
            { RCT2TrackName.BobsleighCoaster, "BOB1" },
            { RCT2TrackName.FlyingTurns, "INTBOB" },
            { RCT2TrackName.ObservationTower, "OBS1" },
            { RCT2TrackName.DoubleDeckObservationTower, "OBS2" },
            { RCT2TrackName.LoopingRollerCoaster, "SCHT1" },
            { RCT2TrackName.DinghySlide, "DING1" },
            { RCT2TrackName.MineTrainCoaster, "AMT1" },
            { RCT2TrackName.ChairliftStandard, "CLIFT1" },
            { RCT2TrackName.CharliftSkiLift, "CLIFT2" },
            { RCT2TrackName.CorkscrewRollerCoaster, "ARRT1" },
            { RCT2TrackName.HyperCoaster, "ARRT2" },
            { RCT2TrackName.Maze, "HMAZE" },
            { RCT2TrackName.SpiralSlide, "HSKELT" },
            { RCT2TrackName.GoKarts, "KART1" },
            { RCT2TrackName.LogFlume, "LFB1" },
            { RCT2TrackName.RiverRapids, "RAPBOAT" },
            { RCT2TrackName.BumperCards, "DODG1" },
            { RCT2TrackName.PirateShip, "SWSH1" },
            { RCT2TrackName.SwingingInverterShip, "SWSH2" },
            { RCT2TrackName.FoodStall, "" },
            { RCT2TrackName.DrinkStall, "" },
            { RCT2TrackName.Shop, "" },
            { RCT2TrackName.MerryGoRound, "MGR1" },
            { RCT2TrackName.InformationKiosk, "" },
            { RCT2TrackName.Bathroom, "" },
            { RCT2TrackName.FerrisWheel, "FWH1" },
            { RCT2TrackName.MotionSimulator, "SIMPOD" },
            { RCT2TrackName.Cinema3D, "C3D" },
            { RCT2TrackName.TopSpin, "TOPSP1" },
            { RCT2TrackName.SpaceRings, "SRINGS" },
            { RCT2TrackName.ReverseFreefallCoaster, "REVF1" },
            { RCT2TrackName.Elevator, "LIFT1" },
            { RCT2TrackName.VerticalDropRollerCoaster, "BMVD" },
            { RCT2TrackName.ATM, "" },
            { RCT2TrackName.Twist, "TWIST1" },
            { RCT2TrackName.SnowCups, "TWIST2" },
            { RCT2TrackName.HauntedHouse, "HHBUILD" },
            { RCT2TrackName.FirstAid, "" },
            { RCT2TrackName.CircusShow, "CIRCUS1" },
            { RCT2TrackName.GhostTrain, "GTC" },
            { RCT2TrackName.HauntedMansionRide, "HMCAR" },
            { RCT2TrackName.TwisterRollerCoaster, "BMSD" },
            { RCT2TrackName.FloorlessRollerCoaster, "BMFL" },
            { RCT2TrackName.StandupTwisterCoaster, "BMSU" },
            { RCT2TrackName.HyperTwisterRollerCoasterWide, "BMRB" },
            { RCT2TrackName.HyperTwisterRollerCoasterNarrow, "GOLTR" },
            { RCT2TrackName.WoodenRollerCoasterArticulated, "MFT" },
            { RCT2TrackName.WoodenRollerCoaster4Seater, "PTCT1" },
            { RCT2TrackName.WoodenRollerCoaster6Seater, "PTCT2" },
            { RCT2TrackName.WoodenRollerCoaster6SeaterReversed, "PTCT2R" },
            { RCT2TrackName.SideFrictionRollerCoaster, "SFRIC1" },
            { RCT2TrackName.WildMouseMouseCars, "SMC1" },
            { RCT2TrackName.WildMouseMineCars, "SMC2" },
            { RCT2TrackName.SpinningWildMouse, "WMSPIN" },
            { RCT2TrackName.MultiDimensionRollerCoaster, "ARRX" },
            { RCT2TrackName.FlyingRollerCoaster, "BMAIR" },
            { RCT2TrackName.VirginiaReel, "VREEL" },
            { RCT2TrackName.SplashBoats, "SPBOAT" },
            { RCT2TrackName.MiniHelicopters, "HELICAR" },
            { RCT2TrackName.LaydownRollerCoaster, "VEKST" },
            { RCT2TrackName.SuspendedMonorail, "SMONO" },
            { RCT2TrackName.ReverserRollerCoaster, "REVCAR" },
            { RCT2TrackName.HeartlineTwisterCoasterStandard, "UTCAR" },
            { RCT2TrackName.HeartlineTwisterCoasterReversed, "UTCARR" },
            { RCT2TrackName.MiniGolf, "GOLF1" },
            { RCT2TrackName.GigaCoaster, "INTST" },
            { RCT2TrackName.RotoDrop, "GDROP1" },
            { RCT2TrackName.FlyingSaucers, "" },
            { RCT2TrackName.CrookedHouse, "CHBUILD" },
            { RCT2TrackName.MonorailCycles, "MONBK" },
            { RCT2TrackName.CompactInvertedCoaster, "SLCT" },
            { RCT2TrackName.InvertedShuttleCoaster, "SLCFO" },
            { RCT2TrackName.WaterCoaster, "CSTBOAT" },
            { RCT2TrackName.AirPoweredVerticalCoaster, "THCAR" },
            { RCT2TrackName.InvertedHairpinCoaster, "IVMC1" },
            { RCT2TrackName.MagicCarpet, "MCARPET1" },
            { RCT2TrackName.SubmarineRide, "SUBMAR" },
            { RCT2TrackName.RiverRafts, "RFTBOAT" },
            { RCT2TrackName.Enterprise, "ENTERP" },
            { RCT2TrackName.InvertedImpulseCoaster, "INTINV" },
            { RCT2TrackName.MiniRollerCoasterAutomobile, "WCATC" },
            { RCT2TrackName.MiniRollerCoasterRocket, "RCKC" },
            { RCT2TrackName.MiniRollerCoasterTobbogan, "JSTAR1" },
            { RCT2TrackName.MineRide, "PMT1" },
            { RCT2TrackName.LIMLaunchedRollerCoaster, "PREMT1" },
        };

        public RCT2RideCode(RCT2RideCode trackType)
        {
            RideType = trackType.RideType;
        }

        public RCT2RideCode()
        {
        }

        public RCT2TrackName RideType { get; set; }
    }
}
